services:
  stats-server:
    build: ./statistic/statistic-server
    container_name: ewm-statistic-server
    ports:
      - "9090:9090"

#  stats-db:
#    image: postgres:16.1

  ewm-service:
    build: ./main-service
    container_name: ewm-main-service
    ports:
      - "8080:8080"

#  ewm-db:
#    image: postgres:16.1
